### ISSUE TITLE
取得できるフィールドの変動が反映されていない

### ISSUE THREAD

**Issue by SuperLazyDog** [trocco-io/embulk-input-yahoo_ads_api#6]
サーバーオプションで広告種類や利用apiのバージョンを指定できるが、
取得できるフィールドは`Column`クラスに固定にされています。

**Comment by SuperLazyDog** [comment]
```yaml
in:
  type: yahoo_ads_api
  client_id: 
  client_secret: 
  refresh_token: 
  servers: https://ads-search.yahooapis.jp/api/v1
  account_id: '877045'
  report_type: AD
  start_date: '20200811'
  end_date: '20200812'
  columns:
  - name: ACCOUNT_NAME
    type: string
    format: ''
  - name: CAMPAIGN_NAME
    type: string
    format: ''
  - name: ADGROUP_NAME
    type: string
    format: ''
  - name: AD_NAME
    type: string
    format: ''
  - name: DEVICE
    type: string
    format: ''
  - name: ACCOUNT_ID
    type: string
    format: ''
  - name: CAMPAIGN_ID
    type: string
    format: ''
  - name: ADGROUP_ID
    type: string
    format: ''
  - name: AD_ID
    type: string
    format: ''
  - name: DAY
    type: string
    format: ''
  - name: TRACKING_URL
    type: string
    format: ''
  - name: IMPS
    type: double
    format: ''
  - name: CLICKS
    type: double
    format: ''
  - name: COST
    type: double
    format: ''
  - name: CONVERSIONS
    type: double
    format: ''
  - name: CONV_VALUE
    type: double
    format: ''
out:
  type: stdout
```
では`ACCOUNT_NAME`はColumn.adにないのでコケてしまっています。
